url : "https://hajekim.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"

title: hajestack
author: Haje Kim
email: hajekim1@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage
# baseurl: /haje

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Haje Kim
  tagline: Solutions Architect. Data Engineer
  disqus_shortname: games
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false
  navigation:
    - title: My Work
      url: "/my-work"
    - title: Resume
      url: "/resume"

  # generate social links in footer
  social_links:
    twitter: haje_kim
    github:  hajekim
    linkedIn: in/hajekim
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed